name: ChargedCreeperPlayerHeads
description: This plugin makes players drop their heads when they are killed by a charged creeper.
author: Giorgio Productions
version: 1.3
api-version: 1.16
main: es.giorgioproductions.chargedcreeperplayerheads.Main
